//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AraturkaMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AraturkaMaster.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miusov, as a man man of breeding and deilcacy, could not but feel some inwrd qualms, when he reached the Father Superior&apos;s with Ivan: he felt ashamed of havin lost his temper. He felt that he ought to have disdaimed that despicable wretch, Fyodor Pavlovitch, too much to have been upset by him in Father Zossima&apos;s cell, and so to have forgotten himself. &quot;Teh monks were not to blame, in any case, &quot; he reflceted, on the steps. &quot;And if they&apos;re decent people here (and the Father Superior, I understand, is a noble [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleText {
            get {
                return ResourceManager.GetString("ExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;n
        ///aan
        ///af
        ///al
        ///as
        ///baie
        ///by
        ///daar
        ///dag
        ///dat
        ///die
        ///dit
        ///een
        ///ek
        ///en
        ///gaan
        ///gesê
        ///haar
        ///het
        ///hom
        ///hulle
        ///hy
        ///in
        ///is
        ///jou
        ///jy
        ///kan
        ///kom
        ///ma
        ///maar
        ///met
        ///my
        ///na
        ///nie
        ///om
        ///ons
        ///op
        ///saam
        ///sal
        ///se
        ///sien
        ///so
        ///sy
        ///te
        ///toe
        ///uit
        ///van
        ///vir
        ///was
        ///wat
        ///ŉ
        ///a
        ///amma
        ///ba
        ///ban
        ///ce
        ///cikin
        ///da
        ///don
        ///ga
        ///in
        ///ina
        ///ita
        ///ji
        ///ka
        ///ko
        ///kuma
        ///lokacin
        ///ma
        ///mai
        ///na
        ///ne
        ///ni
        ///sai
        ///shi
        ///su
        ///suka
        ///sun
        ///ta
        ///tafi
        ///take
        ///tana
        ///wani
        ///wannan
        ///wata
        ///ya
        ///yake
        ///yana
        ///yi
        ///za
        ///aad
        ///albaabkii
        ///atabo
        ///ay
        ///ayaa
        ///ayee
        ///ayuu
        ///dhan
        ///hadana
        ///in
        ///inuu
        ///isku        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stopwords {
            get {
                return ResourceManager.GetString("stopwords", resourceCulture);
            }
        }
    }
}
