#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AraturkaMaster
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="searcher_db")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSiteSitesi(SiteSitesi instance);
    partial void UpdateSiteSitesi(SiteSitesi instance);
    partial void DeleteSiteSitesi(SiteSitesi instance);
    partial void InsertWebSayfa(WebSayfa instance);
    partial void UpdateWebSayfa(WebSayfa instance);
    partial void DeleteWebSayfa(WebSayfa instance);
    partial void InsertWebSite(WebSite instance);
    partial void UpdateWebSite(WebSite instance);
    partial void DeleteWebSite(WebSite instance);
    partial void InsertAnahtarIfade(AnahtarIfade instance);
    partial void UpdateAnahtarIfade(AnahtarIfade instance);
    partial void DeleteAnahtarIfade(AnahtarIfade instance);
    partial void InsertSayfaAnahtari(SayfaAnahtari instance);
    partial void UpdateSayfaAnahtari(SayfaAnahtari instance);
    partial void DeleteSayfaAnahtari(SayfaAnahtari instance);
    #endregion
		
		public DBDataContext() : 
				base(global::AraturkaMaster.Properties.Settings.Default.searcher_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SiteSitesi> SiteSiteleri
		{
			get
			{
				return this.GetTable<SiteSitesi>();
			}
		}
		
		public System.Data.Linq.Table<WebSayfa> WebSayfalar
		{
			get
			{
				return this.GetTable<WebSayfa>();
			}
		}
		
		public System.Data.Linq.Table<WebSite> WebSiteler
		{
			get
			{
				return this.GetTable<WebSite>();
			}
		}
		
		public System.Data.Linq.Table<AnahtarIfade> AnahtarIfadeler
		{
			get
			{
				return this.GetTable<AnahtarIfade>();
			}
		}
		
		public System.Data.Linq.Table<SayfaAnahtari> SayfaAnahtarlari
		{
			get
			{
				return this.GetTable<SayfaAnahtari>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SiteSitesi")]
	public partial class SiteSitesi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _site1;
		
		private System.Guid _site2;
		
		private EntityRef<WebSayfa> _WebSayfalar;
		
		private EntityRef<WebSayfa> _WebSayfa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void Onsite1Changing(System.Guid value);
    partial void Onsite1Changed();
    partial void Onsite2Changing(System.Guid value);
    partial void Onsite2Changed();
    #endregion
		
		public SiteSitesi()
		{
			this._WebSayfalar = default(EntityRef<WebSayfa>);
			this._WebSayfa = default(EntityRef<WebSayfa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType= "UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site1", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid site1
		{
			get
			{
				return this._site1;
			}
			set
			{
				if ((this._site1 != value))
				{
					if (this._WebSayfalar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsite1Changing(value);
					this.SendPropertyChanging();
					this._site1 = value;
					this.SendPropertyChanged("site1");
					this.Onsite1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site2", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid site2
		{
			get
			{
				return this._site2;
			}
			set
			{
				if ((this._site2 != value))
				{
					if (this._WebSayfa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsite2Changing(value);
					this.SendPropertyChanging();
					this._site2 = value;
					this.SendPropertyChanged("site2");
					this.Onsite2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WebSayfalar_SiteSitesi", Storage="_WebSayfalar", ThisKey="site1", OtherKey="Id", IsForeignKey=true)]
		public WebSayfa WebSayfalar
		{
			get
			{
				return this._WebSayfalar.Entity;
			}
			set
			{
				WebSayfa previousValue = this._WebSayfalar.Entity;
				if (((previousValue != value) 
							|| (this._WebSayfalar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WebSayfalar.Entity = null;
						previousValue.SiteSitesis.Remove(this);
					}
					this._WebSayfalar.Entity = value;
					if ((value != null))
					{
						value.SiteSitesis.Add(this);
						this._site1 = value.Id;
					}
					else
					{
						this._site1 = default(System.Guid);
					}
					this.SendPropertyChanged("WebSayfalar");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WebSayfalar_SiteSitesi1", Storage="_WebSayfa", ThisKey="site2", OtherKey="Id", IsForeignKey=true)]
		public WebSayfa WebSayfa
		{
			get
			{
				return this._WebSayfa.Entity;
			}
			set
			{
				WebSayfa previousValue = this._WebSayfa.Entity;
				if (((previousValue != value) 
							|| (this._WebSayfa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WebSayfa.Entity = null;
						previousValue.SiteSitesis1.Remove(this);
					}
					this._WebSayfa.Entity = value;
					if ((value != null))
					{
						value.SiteSitesis1.Add(this);
						this._site2 = value.Id;
					}
					else
					{
						this._site2 = default(System.Guid);
					}
					this.SendPropertyChanged("WebSayfa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WebSayfalar")]
	public partial class WebSayfa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _url;
		
		private System.Guid _website_id;
		
		private string _path;
		
		private string _query;
		
		private string _uzanti;
		
		private string _baslik;
		
		private string _aciklama;
		
		private string _icerik;
		
		private string _content_type;
		
		private System.Nullable<int> _response_code;
		
		private bool _scanned;
		
		private EntitySet<SiteSitesi> _SiteSitesis;
		
		private EntitySet<SiteSitesi> _SiteSitesis1;
		
		private EntitySet<SayfaAnahtari> _SayfaAnahtaris;
		
		private EntityRef<WebSite> _WebSite;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void Onwebsite_idChanging(System.Guid value);
    partial void Onwebsite_idChanged();
    partial void OnpathChanging(string value);
    partial void OnpathChanged();
    partial void OnqueryChanging(string value);
    partial void OnqueryChanged();
    partial void OnuzantiChanging(string value);
    partial void OnuzantiChanged();
    partial void OnbaslikChanging(string value);
    partial void OnbaslikChanged();
    partial void OnaciklamaChanging(string value);
    partial void OnaciklamaChanged();
    partial void OnicerikChanging(string value);
    partial void OnicerikChanged();
    partial void Oncontent_typeChanging(string value);
    partial void Oncontent_typeChanged();
    partial void Onresponse_codeChanging(System.Nullable<int> value);
    partial void Onresponse_codeChanged();
    partial void OnscannedChanging(bool value);
    partial void OnscannedChanged();
    #endregion
		
		public WebSayfa()
		{
			this._SiteSitesis = new EntitySet<SiteSitesi>(new Action<SiteSitesi>(this.attach_SiteSitesis), new Action<SiteSitesi>(this.detach_SiteSitesis));
			this._SiteSitesis1 = new EntitySet<SiteSitesi>(new Action<SiteSitesi>(this.attach_SiteSitesis1), new Action<SiteSitesi>(this.detach_SiteSitesis1));
			this._SayfaAnahtaris = new EntitySet<SayfaAnahtari>(new Action<SayfaAnahtari>(this.attach_SayfaAnahtaris), new Action<SayfaAnahtari>(this.detach_SayfaAnahtaris));
			this._WebSite = default(EntityRef<WebSite>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid website_id
		{
			get
			{
				return this._website_id;
			}
			set
			{
				if ((this._website_id != value))
				{
					if (this._WebSite.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onwebsite_idChanging(value);
					this.SendPropertyChanging();
					this._website_id = value;
					this.SendPropertyChanged("website_id");
					this.Onwebsite_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_path", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string path
		{
			get
			{
				return this._path;
			}
			set
			{
				if ((this._path != value))
				{
					this.OnpathChanging(value);
					this.SendPropertyChanging();
					this._path = value;
					this.SendPropertyChanged("path");
					this.OnpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_query", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string query
		{
			get
			{
				return this._query;
			}
			set
			{
				if ((this._query != value))
				{
					this.OnqueryChanging(value);
					this.SendPropertyChanging();
					this._query = value;
					this.SendPropertyChanged("query");
					this.OnqueryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uzanti", DbType="NVarChar(64)")]
		public string uzanti
		{
			get
			{
				return this._uzanti;
			}
			set
			{
				if ((this._uzanti != value))
				{
					this.OnuzantiChanging(value);
					this.SendPropertyChanging();
					this._uzanti = value;
					this.SendPropertyChanged("uzanti");
					this.OnuzantiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baslik", DbType="NVarChar(1024)")]
		public string baslik
		{
			get
			{
				return this._baslik;
			}
			set
			{
				if ((this._baslik != value))
				{
					this.OnbaslikChanging(value);
					this.SendPropertyChanging();
					this._baslik = value;
					this.SendPropertyChanged("baslik");
					this.OnbaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string aciklama
		{
			get
			{
				return this._aciklama;
			}
			set
			{
				if ((this._aciklama != value))
				{
					this.OnaciklamaChanging(value);
					this.SendPropertyChanging();
					this._aciklama = value;
					this.SendPropertyChanged("aciklama");
					this.OnaciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icerik", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string icerik
		{
			get
			{
				return this._icerik;
			}
			set
			{
				if ((this._icerik != value))
				{
					this.OnicerikChanging(value);
					this.SendPropertyChanging();
					this._icerik = value;
					this.SendPropertyChanged("icerik");
					this.OnicerikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_type", DbType="NVarChar(256)")]
		public string content_type
		{
			get
			{
				return this._content_type;
			}
			set
			{
				if ((this._content_type != value))
				{
					this.Oncontent_typeChanging(value);
					this.SendPropertyChanging();
					this._content_type = value;
					this.SendPropertyChanged("content_type");
					this.Oncontent_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_response_code", DbType="Int")]
		public System.Nullable<int> response_code
		{
			get
			{
				return this._response_code;
			}
			set
			{
				if ((this._response_code != value))
				{
					this.Onresponse_codeChanging(value);
					this.SendPropertyChanging();
					this._response_code = value;
					this.SendPropertyChanged("response_code");
					this.Onresponse_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scanned", DbType="Bit NOT NULL")]
		public bool scanned
		{
			get
			{
				return this._scanned;
			}
			set
			{
				if ((this._scanned != value))
				{
					this.OnscannedChanging(value);
					this.SendPropertyChanging();
					this._scanned = value;
					this.SendPropertyChanged("scanned");
					this.OnscannedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WebSayfalar_SiteSitesi", Storage="_SiteSitesis", ThisKey="Id", OtherKey="site1")]
		public EntitySet<SiteSitesi> SiteSitesis
		{
			get
			{
				return this._SiteSitesis;
			}
			set
			{
				this._SiteSitesis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WebSayfalar_SiteSitesi1", Storage="_SiteSitesis1", ThisKey="Id", OtherKey="site2")]
		public EntitySet<SiteSitesi> SiteSitesis1
		{
			get
			{
				return this._SiteSitesis1;
			}
			set
			{
				this._SiteSitesis1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WebSayfalar_SayfaAnahtarlari", Storage="_SayfaAnahtaris", ThisKey="Id", OtherKey="sayfa_id")]
		public EntitySet<SayfaAnahtari> SayfaAnahtaris
		{
			get
			{
				return this._SayfaAnahtaris;
			}
			set
			{
				this._SayfaAnahtaris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WebSiteler_WebSayfalar", Storage="_WebSite", ThisKey="website_id", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public WebSite WebSite
		{
			get
			{
				return this._WebSite.Entity;
			}
			set
			{
				WebSite previousValue = this._WebSite.Entity;
				if (((previousValue != value) 
							|| (this._WebSite.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WebSite.Entity = null;
						previousValue.WebSayfas.Remove(this);
					}
					this._WebSite.Entity = value;
					if ((value != null))
					{
						value.WebSayfas.Add(this);
						this._website_id = value.Id;
					}
					else
					{
						this._website_id = default(System.Guid);
					}
					this.SendPropertyChanged("WebSite");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SiteSitesis(SiteSitesi entity)
		{
			this.SendPropertyChanging();
			entity.WebSayfalar = this;
		}
		
		private void detach_SiteSitesis(SiteSitesi entity)
		{
			this.SendPropertyChanging();
			entity.WebSayfalar = null;
		}
		
		private void attach_SiteSitesis1(SiteSitesi entity)
		{
			this.SendPropertyChanging();
			entity.WebSayfa = this;
		}
		
		private void detach_SiteSitesis1(SiteSitesi entity)
		{
			this.SendPropertyChanging();
			entity.WebSayfa = null;
		}
		
		private void attach_SayfaAnahtaris(SayfaAnahtari entity)
		{
			this.SendPropertyChanging();
			entity.WebSayfa = this;
		}
		
		private void detach_SayfaAnahtaris(SayfaAnahtari entity)
		{
			this.SendPropertyChanging();
			entity.WebSayfa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WebSiteler")]
	public partial class WebSite : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _url;
		
		private EntitySet<WebSayfa> _WebSayfas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    #endregion
		
		public WebSite()
		{
			this._WebSayfas = new EntitySet<WebSayfa>(new Action<WebSayfa>(this.attach_WebSayfas), new Action<WebSayfa>(this.detach_WebSayfas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WebSiteler_WebSayfalar", Storage="_WebSayfas", ThisKey="Id", OtherKey="website_id")]
		public EntitySet<WebSayfa> WebSayfas
		{
			get
			{
				return this._WebSayfas;
			}
			set
			{
				this._WebSayfas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_WebSayfas(WebSayfa entity)
		{
			this.SendPropertyChanging();
			entity.WebSite = this;
		}
		
		private void detach_WebSayfas(WebSayfa entity)
		{
			this.SendPropertyChanging();
			entity.WebSite = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AnahtarIfadeler")]
	public partial class AnahtarIfade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _ifade;
		
		private EntitySet<SayfaAnahtari> _SayfaAnahtaris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnifadeChanging(string value);
    partial void OnifadeChanged();
    #endregion
		
		public AnahtarIfade()
		{
			this._SayfaAnahtaris = new EntitySet<SayfaAnahtari>(new Action<SayfaAnahtari>(this.attach_SayfaAnahtaris), new Action<SayfaAnahtari>(this.detach_SayfaAnahtaris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ifade", DbType="NVarChar(2048) NOT NULL", CanBeNull=false)]
		public string ifade
		{
			get
			{
				return this._ifade;
			}
			set
			{
				if ((this._ifade != value))
				{
					this.OnifadeChanging(value);
					this.SendPropertyChanging();
					this._ifade = value;
					this.SendPropertyChanged("ifade");
					this.OnifadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AnahtarIfadeler_SayfaAnahtarlari", Storage="_SayfaAnahtaris", ThisKey="Id", OtherKey="ifade_id")]
		public EntitySet<SayfaAnahtari> SayfaAnahtaris
		{
			get
			{
				return this._SayfaAnahtaris;
			}
			set
			{
				this._SayfaAnahtaris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SayfaAnahtaris(SayfaAnahtari entity)
		{
			this.SendPropertyChanging();
			entity.AnahtarIfade = this;
		}
		
		private void detach_SayfaAnahtaris(SayfaAnahtari entity)
		{
			this.SendPropertyChanging();
			entity.AnahtarIfade = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SayfaAnahtarlari")]
	public partial class SayfaAnahtari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _ifade_id;
		
		private System.Guid _sayfa_id;
		
		private double _puan;
		
		private EntityRef<AnahtarIfade> _AnahtarIfade;
		
		private EntityRef<WebSayfa> _WebSayfa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void Onifade_idChanging(System.Guid value);
    partial void Onifade_idChanged();
    partial void Onsayfa_idChanging(System.Guid value);
    partial void Onsayfa_idChanged();
    partial void OnpuanChanging(double value);
    partial void OnpuanChanged();
    #endregion
		
		public SayfaAnahtari()
		{
			this._AnahtarIfade = default(EntityRef<AnahtarIfade>);
			this._WebSayfa = default(EntityRef<WebSayfa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ifade_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ifade_id
		{
			get
			{
				return this._ifade_id;
			}
			set
			{
				if ((this._ifade_id != value))
				{
					if (this._AnahtarIfade.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onifade_idChanging(value);
					this.SendPropertyChanging();
					this._ifade_id = value;
					this.SendPropertyChanged("ifade_id");
					this.Onifade_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sayfa_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid sayfa_id
		{
			get
			{
				return this._sayfa_id;
			}
			set
			{
				if ((this._sayfa_id != value))
				{
					if (this._WebSayfa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsayfa_idChanging(value);
					this.SendPropertyChanging();
					this._sayfa_id = value;
					this.SendPropertyChanged("sayfa_id");
					this.Onsayfa_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puan", DbType="Float NOT NULL")]
		public double puan
		{
			get
			{
				return this._puan;
			}
			set
			{
				if ((this._puan != value))
				{
					this.OnpuanChanging(value);
					this.SendPropertyChanging();
					this._puan = value;
					this.SendPropertyChanged("puan");
					this.OnpuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AnahtarIfadeler_SayfaAnahtarlari", Storage="_AnahtarIfade", ThisKey="ifade_id", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public AnahtarIfade AnahtarIfade
		{
			get
			{
				return this._AnahtarIfade.Entity;
			}
			set
			{
				AnahtarIfade previousValue = this._AnahtarIfade.Entity;
				if (((previousValue != value) 
							|| (this._AnahtarIfade.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AnahtarIfade.Entity = null;
						previousValue.SayfaAnahtaris.Remove(this);
					}
					this._AnahtarIfade.Entity = value;
					if ((value != null))
					{
						value.SayfaAnahtaris.Add(this);
						this._ifade_id = value.Id;
					}
					else
					{
						this._ifade_id = default(System.Guid);
					}
					this.SendPropertyChanged("AnahtarIfade");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WebSayfalar_SayfaAnahtarlari", Storage="_WebSayfa", ThisKey="sayfa_id", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public WebSayfa WebSayfa
		{
			get
			{
				return this._WebSayfa.Entity;
			}
			set
			{
				WebSayfa previousValue = this._WebSayfa.Entity;
				if (((previousValue != value) 
							|| (this._WebSayfa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WebSayfa.Entity = null;
						previousValue.SayfaAnahtaris.Remove(this);
					}
					this._WebSayfa.Entity = value;
					if ((value != null))
					{
						value.SayfaAnahtaris.Add(this);
						this._sayfa_id = value.Id;
					}
					else
					{
						this._sayfa_id = default(System.Guid);
					}
					this.SendPropertyChanged("WebSayfa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
